query artistAlbums($artistId: MBID!) {
  lookup {
    artist(mbid: $artistId) {
      name
      releaseGroups(type: ALBUM) {
        nodes {
          title
          firstReleaseDate
          # tags {
          #   nodes {
          #     count
          #     name
          #   }
          # }
          discogs {
            images {
              thumbnail
            }
          }
        }
      }
    }
  }
}
